version: '3'

services:
  redis:
    image: 'redis:6.2.1-alpine'
    command: redis-server --requirepass devpassword
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

  website:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "arcana.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/arcana'
    ports:
      - '8000:8000'

  celery:
    build: .
    command: celery -A arcana.blueprints.contact.tasks worker
    env_file:
      - '.env'
    volumes:
      - '.:/arcana'

volumes:
  redis: